# Generated by Django 5.0.1 on 2024-02-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_jobs', '0002_alter_joblisting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='date_job_post',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='date_of_scrap',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(max_length=100),
        ),
    ]
