# Generated by Django 5.0.1 on 2024-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_jobs', '0003_alter_joblisting_date_job_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
    ]
