# Generated by Django 5.0.1 on 2024-02-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_jobs', '0004_alter_joblisting_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='company_id',
        ),
    ]
