# Generated by Django 5.0.1 on 2024-02-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_jobs', '0005_remove_joblisting_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='source_id',
        ),
    ]
