# Generated by Django 5.0.1 on 2024-02-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_jobs', '0006_remove_joblisting_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
